//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IANSEO_Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IANSEO_Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close IANSEO.
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🔗 Copy.
        /// </summary>
        public static string BtnCopyLink {
            get {
                return ResourceManager.GetString("BtnCopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open XAMPP Control.
        /// </summary>
        public static string BtnOpenXamppControl {
            get {
                return ResourceManager.GetString("BtnOpenXamppControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📸 QR-Code.
        /// </summary>
        public static string BtnShowQR {
            get {
                return ResourceManager.GetString("BtnShowQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🌐 Open IANSEO.
        /// </summary>
        public static string BtnStartOpen_Open {
            get {
                return ResourceManager.GetString("BtnStartOpen_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ▶️ Start IANSEO.
        /// </summary>
        public static string BtnStartOpen_Run {
            get {
                return ResourceManager.GetString("BtnStartOpen_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⏳ Starting....
        /// </summary>
        public static string BtnStartOpen_Starting {
            get {
                return ResourceManager.GetString("BtnStartOpen_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⏸️ Stop IANSEO.
        /// </summary>
        public static string BtnStop {
            get {
                return ResourceManager.GetString("BtnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⏳ Stopping....
        /// </summary>
        public static string BtnStop_Stopping {
            get {
                return ResourceManager.GetString("BtnStop_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copied.
        /// </summary>
        public static string Copied_Title {
            get {
                return ResourceManager.GetString("Copied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        public static System.Drawing.Icon ianseo {
            get {
                object obj = ResourceManager.GetObject("ianseo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Directory.
        /// </summary>
        public static string InvalidDirectory_Title {
            get {
                return ResourceManager.GetString("InvalidDirectory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IANSEO server address.
        /// </summary>
        public static string LblAddress {
            get {
                return ResourceManager.GetString("LblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apache.
        /// </summary>
        public static string LblApache {
            get {
                return ResourceManager.GetString("LblApache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service status.
        /// </summary>
        public static string LblEtat {
            get {
                return ResourceManager.GetString("LblEtat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MySQL.
        /// </summary>
        public static string LblMySQL {
            get {
                return ResourceManager.GetString("LblMySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during copy:.
        /// </summary>
        public static string Msg_Error_Copy {
            get {
                return ResourceManager.GetString("Msg_Error_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during execution:.
        /// </summary>
        public static string Msg_Error_Execution {
            get {
                return ResourceManager.GetString("Msg_Error_Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error opening browser:.
        /// </summary>
        public static string Msg_Error_OpenBrowser {
            get {
                return ResourceManager.GetString("Msg_Error_OpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error opening the browser:.
        /// </summary>
        public static string Msg_Error_OpenBrowserAlt {
            get {
                return ResourceManager.GetString("Msg_Error_OpenBrowserAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error opening XAMPP Control: .
        /// </summary>
        public static string Msg_Error_OpenXamppControl {
            get {
                return ResourceManager.GetString("Msg_Error_OpenXamppControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error generating QR code:.
        /// </summary>
        public static string Msg_Error_QrGeneration {
            get {
                return ResourceManager.GetString("Msg_Error_QrGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IANSEO.exe is not in the &quot;ianseo\&quot; folder or &quot;Xampp-control.exe&quot; is missing.
        ///
        ///Usually, the &quot;ianseo\&quot; folder is located in &quot;C:\&quot; as recommended during installation.
        ///
        ///Please place this executable in that folder and make sure that Xampp-control.exe is also present in the same folder..
        /// </summary>
        public static string Msg_InvalidDirectory {
            get {
                return ResourceManager.GetString("Msg_InvalidDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Link copied to clipboard.
        /// </summary>
        public static string Msg_LinkCopied {
            get {
                return ResourceManager.GetString("Msg_LinkCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IANSEO QR Code.
        /// </summary>
        public static string QrForm_Title {
            get {
                return ResourceManager.GetString("QrForm_Title", resourceCulture);
            }
        }
    }
}
